//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ent_EFDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class extable
    {
        public int id { get; set; }
        public string name { get; set; }
        public int value { get; set; }
        public System.DateTime time { get; set; }
    }
}
